### PR TITLE
trying to fix #52, ConnectionPoolTimeoutException

### LINKED ISSUE #52: ConnectionPoolTimeoutException
First I thought this is an external problem, but it seems that after a few errors on the external API (like unreachability or similar) dropwizard is no longer able to get a new connection and always fails with:

```
! Causing: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
! at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:109)
```
 
 - [x] set up better monitoring
 - [ ] Highly like because we do not close certain connections somewhere. At least [SO is telling me this](https://stackoverflow.com/q/11875015).

### PR DESCRIPTION
**Pull request by karussell**

### CODE REVIEW

File: src/main/java/com/graphhopper/converter/resources/AbstractConverterResource.java [hunk 1]
```diff
@@ -67,11 +70,14 @@ boolean isValid(Locale locale) {
         }
     }
 
-    void failIfResponseNotSuccessful(WebTarget target, Status status) {
-        // TODO Maybe limit to == 200?
+    Status failIfResponseNotSuccessful(WebTarget target, Response response) {
+        Status status = new Status(response.getStatus(), response.getStatusInfo().getReasonPhrase());
         if (status.code < 200 || status.code >= 300) {
+            // avoid connection leaks, see #52
+            response.close();
```
Comment (karussell) [inline src/main/java/com/graphhopper/converter/resources/AbstractConverterResource.java:77]: SO suggests that we have to consume the response, but IMO close is sufficient. WDYT?

Comment (boldtrn) [reply src/main/java/com/graphhopper/converter/resources/AbstractConverterResource.java:77]: It looks like closing should be enough. 

The [JavaDoc](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Response.html#close--) states:
> Close the underlying message entity input stream (if available and open) as well as releases any other resources associated with the response (e.g. buffered message entity data).

Also the [getEntity](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Response.html#getEntity--) method describes:
> IllegalStateException - if the entity was previously fully consumed as an input stream, or if the response has been closed.

It makes sense that we cannot read the entity of a closed response. So it cannot be consumed anymore. So I think it's safe to assume that it should be released from the ConnectionPool.

I guess it would make sense to first only try to close the response. If it doesn't fix the connection leak, we can still read the entity. But I am pretty sure closing should be enough.

File: src/main/java/com/graphhopper/converter/resources/ConverterResourceGisgraphy.java [hunk 2]
```diff
@@ -87,84 +82,80 @@ public Response handle(@QueryParam("q") @DefaultValue("") String query,
...
         } catch (Exception e) {
-            LOGGER.error("There was an issue with the target "
-                    + target.getUri() + " the provider returned: "
-                    + status.code + " - " + status.message);
-            throw new BadRequestException(
-                    "error deserializing geocoding feed");
+            LOGGER.error("There was an issue with the target " + target.getUri() + " the provider returned: " + status.code + " - " + status.message);
+            throw new BadRequestException("error deserializing geocoding feed");
+        } finally {
+            response.close();
```
Comment (boldtrn) [inline src/main/java/com/graphhopper/converter/resources/ConverterResourceGisgraphy.java:101]: Good catch!

**Comment by boldtrn** [comment]
I fixed the CI tests. There was an issue with the OCD key. I updated the key and the test seem to run fine.

**Review by boldtrn — APPROVED** [review]

**Comment by karussell** [comment]
Thanks a lot for the review!
