### PR TITLE
Check response code of geocoding provider

### LINKED ISSUE #28: How to handle exceptions from our providers?
For example in #26 we requested an URL from Nominatim.
`http://nominatim.openstreetmap.org/reverse/?lat=NaN&lon=NaN&limit=5&format=json&email=&addressdetails=1&accept-language=en`

Nominatim returned an exception for this request. We try to convert that request to a regular response, which leads to an Exception. 

I think we should check the response code of the provider an either return a 400 ourselves or maybe even forward the exception of the provider? (Not sure if we want to do this due to security?)

### PR DESCRIPTION
**Pull request by boldtrn**
Fixes #28.

We check the response code of the provider. If the response code is not equal to 2XX, we return a 400, with a generic exception message. We log the request as Error and ask the user to contact the support.

WDYT?

### CODE REVIEW

File: src/main/java/com/graphhopper/converter/resources/AbstractConverterResource.java [hunk 1]
```diff
@@ -59,4 +66,12 @@ boolean isValid(Locale locale) {
             return false;
         }
     }
+
+    void failIfResponseNotSuccessful(WebTarget target, Status status) {
+        // TODO Maybe limit to == 200?
+        if (status.code < 200 || status.code >= 300) {
+            LOGGER.error("There was an issue with the target " + target.getUri() + " the provider returned: " + status.code + " - " + status.message);
+            throw new BadRequestException("The geocoding provider responded with an unexpected error. If this error happens again, please contact our support team support@graphhopper.com.");
```
Comment (karussell) [inline src/main/java/com/graphhopper/converter/resources/AbstractConverterResource.java]: You can omit: 'If this error ...'

**Comment by karussell** [comment]
Thanks looks good!

File: src/main/java/com/graphhopper/converter/resources/AbstractConverterResource.java (hunk 1 above)
Comment (boldtrn) [reply src/main/java/com/graphhopper/converter/resources/AbstractConverterResource.java]: You mean like this?

**Comment by boldtrn** [comment]
Thanks for the reivew :)

**Comment by karussell** [comment]
> You mean like this?

Ups, I meant completely without this sentence. Because we normally see those errors, no need to contact us.

**Comment by boldtrn** [comment]
> Ups, I meant completely without this sentence. Because we normally see those errors, no need to contact us.

Ah, wasn't sure. Should be fine now, will merge this PR.
